name: CD Pipeline 

on: 
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull wcbongz/aws_cicd_test:latest
    - name: Disable AppArmor
      run: sudo systemctl disable apparmor.service --now
    - name: unload AppArmor Profiles
      run: sudo service apparmor teardown
    - name: Delete Old Container
      run: sudo docker rm -f aws_cicd_test || true
    - name: Run Container
      run : docker run -d -p 8080:8080 --name aws_cicd_test wcbongz/aws_cicd_test