name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}


    - name: Build the Docker image
      run: docker build -t wcbongz/aws_cicd_test:latest .

    - name: Push to Docker Hub
      run: docker push wcbongz/aws_cicd_test:latest
